### ISSUE TITLE
Shift the GitHub action to CLI repository

### ISSUE THREAD

**Issue by Shurtu-gal** [asyncapi/github-action-for-cli#396]
### Why do we need this improvement?

Currently the versions, releases and other stuff are isolated from CLI which is directly coupled with this CLI. However, this creates problems in bumping of versions and keeping code updated as well.

Furthermore, any change in CLI spec could be easily made here as well.

### How will this change help?

This will help in automation of releases of CLI and tie them together properly.

#### This issue can be resolved through the following steps:-
- Transfer the source code of this action in a github-action folder.
- Put the test workflow in its proper place in `.github` directory.
- Tie the version at these steps:
https://github.com/asyncapi/github-action-for-cli/blob/590180ca0d91785af367276558b2b60d86f7d1e2/entrypoint.sh#L29
https://github.com/asyncapi/github-action-for-cli/blob/590180ca0d91785af367276558b2b60d86f7d1e2/Dockerfile#L13
- Add automation for release of new version of action with bump in CLI version.
- Put `action.yml` in root folder.

#### Additional steps:
1. Instead of installing the asyncapi cli, dockerise the code from parent directory itself.

> [!IMPORTANT]
> The action and bump of version would need to be tested in your personal repo or account. From my past experience would suggest using an alternate account itself.

### 🚧 Breaking changes

Yes

**Comment by Shurtu-gal** [comment]
bounty/candidate

**Comment by akshatnema** [comment]
@Shurtu-gal I wish to work on this issue. Basically, want to try something new, apart from website 😅

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal I wish to work on this issue. Basically, want to try something new, apart from website 😅

Great, however would need to wait for it to be accepted before assigning.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q3`, `bounty/medium`, `bounty/coding`
First assignment to third-party contributors: [2024-06-21 00:00:00 UTC+12:00](https://time.lol/#2024-06-21T00:00:00+12:00)
End Of Life after: [2024-07-31 23:59:59 UTC-12:00](https://time.lol/#2024-07-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Third-party contributors should [coherently articulate](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365) how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by Shurtu-gal** [comment]
@asyncapi/bounty_team as per the rules with maintainers having more preference, I have assigned @akshatnema the issue.

**Comment by akshatnema** [comment]
Thanks @Shurtu-gal 😄 👍

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)**        |[2024-07-14](https://time.lol/#2024-07-14T23:59:59-12:00)         |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |**[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by akshatnema** [comment]
Hey @aeworxet,
Can you please extend the deadline of bounty issue by 2 weeks, as I caught Dengue in the previous week?

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2217978504) (@akshatnema), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by akshatnema** [comment]
Thanks @aeworxet

**Comment by Shurtu-gal** [comment]
@akshatnema do you need any help on this ?

**Comment by aeworxet** [comment]
@akshatnema, please provide an update to the [PR](https://github.com/asyncapi/cli/pull/1487).

**Comment by aeworxet** [comment]
@akshatnema, please provide an update to the [PR](https://github.com/asyncapi/cli/pull/1487).

**Comment by aeworxet** [comment]
@akshatnema had scheduled a call with @derberg on 2024-08-27 to clarify some final details on this Bounty Issue before merging https://github.com/asyncapi/cli/pull/1487.

**Comment by aeworxet** [comment]
Response, critical for technical resolution of this Bounty Issue (**clarification on implementation**) was delayed for one period of three consecutive working days
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2307699278

so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-09-08](https://time.lol/#2024-09-08T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)         |**[2024-09-08](https://time.lol/#2024-09-08T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by akshatnema** [comment]
Hey @aeworxet ,
after discussion this with @Shurtu-gal and Lukasz, I find that this may get delayed for the completion. Can you please extend the bounty deadlines by 2 weeks?

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2330754774) (@akshatnema), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
@akshatnema, please provide an update to the [PR](https://github.com/asyncapi/cli/pull/1487).

**Comment by aeworxet** [comment]
> There is no update as I'm researching around the fact on how to manage GitHub Action for CLI.
> 
> @Shurtu-gal and @derberg proposals require different configurations, which in fact means we need to have the same package.json for both CLI and it's respective GitHub action.
> 
> I'm currently looking at how to use only one configuration and one package.json.
> 
> Although the matter looks simple, it will take time to try different approaches, so if I don't achieve a break-through in the nearest couple of days, I'll ask for the Timeline Extension.

https://github.com/asyncapi/cli/pull/1487#issuecomment-2353301910

**Comment by aeworxet** [comment]
The latest conversation with @akshatnema took place on Friday 2024-09-20 in Slack, where he stated that the solution to this Bounty Issue will be merged later because it requires thorough testing, as it is a complete repo being moved into an existing one, and then became unresponsive.

Reasons for sudden silence after a lively conversation can be numerous, so I'm waiting for the clarification on this matter before taking any action.

**Comment by akshatnema** [comment]
Hey @aeworxet Sorry for the late reply.

The solution requires thorough testing, as this is a complete repo being moved into an existing one, so I need an extension by 2 weeks. But most probably, I will do everything on this weekend.

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2371445706) (@akshatnema), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-10-06](https://time.lol/#2024-10-06T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)         |**[2024-10-06](https://time.lol/#2024-10-06T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by Shurtu-gal** [comment]
@aeworxet the versions automation task will be done in another PR.

**Comment by Shurtu-gal** [comment]
@aeworxet this issue is pretty complicated as some things related to containerizing part is still not working and we still have to do the automation of version locking and bumping. @akshatnema is also pretty new to the CLI repo so is it possible to reclassify this bounty as `advanced` and extend it for 1-2 weeks.

P.S: Original Source: https://github.com/asyncapi/cli/pull/1487#issuecomment-2395396217

**Comment by aeworxet** [comment]
Upon [request](https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2395469486) of the AsyncAPI Maintainer (@Shurtu-gal, `githubID` [100484401](https://api.github.com/user/100484401)), the Complexity Level of this Bounty Issue was [reclassified](https://github.com/orgs/asyncapi/discussions/963#discussioncomment-9778034) to `Advanced` (upgraded), and all remaining target dates of its Timeline were extended by two calendar weeks.

### Bounty Issue was Reclassified and its Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Advanced        |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-10-20](https://time.lol/#2024-10-20T23:59:59-12:00)**        |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |[2024-09-22](https://time.lol/#2024-09-22T23:59:59-12:00)         |**[2024-10-20](https://time.lol/#2024-10-20T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR224) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR99).

**Comment by aeworxet** [comment]
Implementation of https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2395440596

> the versions automation task

is the PR

https://github.com/asyncapi/cli/pull/1543

**Comment by aeworxet** [comment]
Timeline for this Bounty Issue has run out. Knowing it is quite complex, and taking into account that both @akshatnema and @Shurtu-gal have remained responsive during its resolution, I must first ask what should be done with it moving forward? Is more time needed to complete it, is it in the final stages, or is there something else?

**Comment by Shurtu-gal** [comment]
> Timeline for this Bounty Issue has run out. Knowing it is quite complex, and taking into account that both @akshatnema and @Shurtu-gal have remained responsive during its resolution, I must first ask what should be done with it moving forward? Is more time needed to complete it, is it in the final stages, or is there something else?

It's in the final stages, just need to get the automation in place.

**Comment by Shurtu-gal** [comment]
This bounty is still in progress. We have been discussing possible solutions and have come with two plausible ones:-

- Using docker image directly to forego the github relase overhead.
- Using changeset to bump action.yml before release

cc: @aeworxet

**Comment by Shurtu-gal** [comment]
@aeworxet @akshatnema is exploring the above mentioned solutions and would be giving any updates he finds out here.

**Comment by aeworxet** [comment]
This Bounty Issue is still in progress and is encountering many restrictions and limitations related to GitHub Actions, AsyncAPI infrastructure, and the release process.

**Comment by akshatnema** [comment]
I tried to create release workflow using changeset here - https://github.com/akshatnema/cli/actions/runs/11999463258/job/33447396874. Currently debugging in it to create a changeset in the fork repo, and test the workflow.

**Comment by Shurtu-gal** [comment]
Update: this weekend we got the the changeset workflow to work regarding bump so it seems promising enough to fulfill all the requirements. The PR for mentioned workflow will be coming soon.

**Comment by Shurtu-gal** [comment]
The PR for said workflow has been created and merged. The changeset is not yet working as intended and @akshatnema is trying to debug it.

**Comment by Shurtu-gal** [comment]
@aeworxet this bounty has been completed.

**Comment by aeworxet** [comment]
After a set of delays that were beyond the control of the Bounty Program Participant

https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2426794619
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2461485869
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2468117918
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2490006384
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2497032782
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2513539523
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2537558011
https://github.com/asyncapi/github-action-for-cli/issues/396#issuecomment-2542902617

### Bounty Issue Is Completed 🎉

@akshatnema (`githubID` [76521428](https://api.github.com/user/76521428)), please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty github-action-for-cli#396`, tag `bounty`, and full URL of this Bounty Issue in the description.
