### ISSUE TITLE
[BUG] AsyncAPI v3 support 

### ISSUE THREAD

**Issue by PedroQwe** [asyncapi/github-action-for-cli#401]
### Describe the bug.

I am trying to use the asyncapi/github-action-for-cli to generate models from a file using AsyncAPI v3 and I am getting this error: `Error: Generate Models command does not support AsyncAPI v3 yet, please checkout https://github.com/asyncapi/modelina/issues/1376`

However, the issue 1376 has already been fixed and asyncapi cli already supports v3.

### Expected behavior

The models should be generated given that asyncapi cli already supports v3.

### Screenshots

![image](https://github.com/user-attachments/assets/94ae1723-baab-4093-9867-0810bb5f8d66)

### How to Reproduce

1. Create a AsyncAPI specification file following v3
2. Create a github action to generate models from the file created in step 1.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by pioneer2k** [comment]
@PedroQwe is there a reason why do you use such an old version of the markdown-template? I think v3 support was coming with the release 1.4.0 of that template. Maybe that is the problem?
We are using the generator with the latest html-template and eveything is working fine with v3 spec files.

**Comment by Shurtu-gal** [comment]
@PedroQwe the problem lies in the version of CLI. 

You have two options:
- Upgrade the version of action you are using to `3.1.2` which works fine [as can be seen here](https://github.com/ash17290/test-repo/actions/runs/10419423863/job/28857439465).
- Pass custom CLI version according to your needs: [Documentation](https://github.com/asyncapi/github-action-for-cli/tree/v3.1.1?tab=readme-ov-file#cli_version)

> [!NOTE]
> FYI: we are working on tying CLI and GitHub action versioning for better experience, so you wouldn't have to face these problems.

**Comment by Shurtu-gal** [comment]
Please let me know if this works and I will move forward with closing this ticket.
